var players = ["Altuve", "Corerra", "Bregman"];
var player_numbers = [25, 3, 2];
console.log(players);
console.log(player_numbers);
var names;
names = ["James Cross", "Jen Ryan", "Abby Cross", "Kaylee Chillders"];
console.log(names);
names = "Jen Ryan";
console.log(names);
var member_names = ["Cross", "Ryan", "Childers"];
var member_age = [42, 30, 15];
console.log(member_names);
console.log(member_age);
var names;
names = ["James Cross", "Jen Ryan", "Abby Cross", "Kaylee Chillders"];
console.log(names);
names = "Jen Ryan";
console.log(names);
